### ISSUE TITLE
geolocation 동의시 위치 변화

### ISSUE THREAD

**Issue by michoball** [Couch-Coders/12th-Fun-Pyeon-log-fe#55]
처음 앱을 사용하면 geolocation 동의를 구하는 창이 나오고 이를 동의하면 사용자의 위치로 이동합니다. 
실사용 앱에서는 당연하지만 
본 프로젝트는 앱을 처음 구동하는 사용자가 먼저 리스트에 정보가 들어와있는 상태를 보여주기 위해
서울역을 처음 위치로 잡고 보여줘야합니다. 
geolocation 동의 후에도 서울역이 보여지도록 수정해야 합니다.

**Comment by thisisyeji** [comment]
해결 완료 -> develop 머지 완료
